# Generated by Django 3.1.3 on 2020-12-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201203_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentPrice',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=9), max_digits=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
